config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :instances
  get '/dashboard' => 'dashboard#index'

  get '/instances' => 'instances#index'
  get '/instance/:id' => 'instances#show'
  post '/instance' => 'instances#create'
  put '/instance/:id' => 'instances#update'
  delete 'instance/:id' => 'instances#destroy'

  get 'user/new'
  get 'users' => 'user#index'
  get 'user/:id' => 'user#show'
  post 'user' => 'user#create'
  put 'user/:id' => 'user#update'
  delete 'user/:id' => 'user#delete'

  root 'session#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/instance.rb
class Instance < ActiveRecord::Base
end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  before_action :authorize
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  #before_action :set_instance, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :create, :update, :destroy]
  # GET /instances
  # GET /instances.json
  def index
    @instances = Instance.all
    render :json => @instances
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @instance = Instance.find(params[:id])
    render :json =>@instance
  end

  # GET /instances/new
  def new
    @instance = Instance.new
  end

  # GET /instances/1/edit
  def edit
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(instance_params)

    #respond_to do |format|
      if @instance.save
        #format.html { redirect_to @instance, notice: 'Instance was successfully created.' }
        #format.json { render :show, status: :created, location: @instance }
	@response = { :message => "Instance successfully created."}
	render :json => @response 
      else
        #format.html { render :new }
        render :json => @instance.errors
      end
    #end
  end

  # PATCH/PUT /instances/1
  # PATCH/PUT /instances/1.json
  def update
	@instance = Instance.find(params[:id])
    #respond_to do |format|
      if @instance.update_attributes(instance_params)
        #format.html { redirect_to @instance, notice: 'Instance was successfully updated.' }
        #format.json { render :show, status: :ok, location: @instance }
	@response = { :message => "Instance successfully updated."}
	render :json => @response
      else
        #format.html { render :edit }
        render :json => @instance.errors
      end
    #end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    Instance.find(params[:id]).destroy
    #respond_to do |format|
      #format.html { redirect_to instances_url, notice: 'Instance was successfully destroyed.' }
      #format.json { head :no_content }
      @response = { :message =>"Instance successfully destroyed."}
      render :json => @response
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_params
      params.permit(:ip_address, :image, :launch_time, :status)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :create, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    render :json => @properties
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    #respond_to do |format|
      if @property.save
	@response = {:status => "201", :message => "Property successfully created."}
	render :json => @response
      else
	render :json => @user.errors
      end
    #end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    @property = Property.find(params[:id])
    #respond_to do |format|
      if @property.update_attributes(property_params)
        @response = { :message => "Property successfully updated." }
	render :json => @response
      else
        #format.html { render :edit }
        render :json => @property.errors
      end
    #end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    Property.find(params[:id]).destroy
    #respond_to do |format|
     #format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
     #format.json { head :no_content }
    #end
    @response = { :message => "Property successfully deleted." }
    render :json => @response
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.permit(:varable, :value)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by_email_and_password(params[:email], params[:password])
    # If the user exists AND the password entered is correct.
    if user
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/dashboard'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :authorize, only: [:index, :create, :update, :delete]
  require 'json'
  def new
  end
  #GET /users
  def index
	@users = User.all
	render :json => @users
	#respond_to do |format|
		#format.html do
		#	redirect_to '/dashboard'
		#end
		#format.json {render json: @users}
	#end
  end
  #GET user/id
  def show
	@user = User.find(params[:id])
	render :json => @user
  end
  
   
  #POST /user
  def create
	@user = User.new(user_params)
	
	if @user.save
		@response = {:status => "201", :message => "User successfully created."}
		render :json => @response
	else
		render :json => @user.errors
	end
  end
  
  def user_params
	params.permit(:email, :password)
  end
  
  #PUT /user/id
  def update
	@user = User.find(params[:id])
	
	if @user.update_attributes(user_param)
		@response = { :message => "User successfully updated." }
		render :json => @response
	else
		render :json => @user.errors
	end
  end
  
   def user_param
	params.permit(:email, :password)
   end
  
  #DELETE /user/id
  def delete
	User.find(params[:id]).destroy
	
	@response = { :message => "User successfully deleted." }
	render :json => @response
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/instances/_form.html.erb
<%= form_for(@instance) do |f| %>
  <% if @instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance.errors.count, "error") %> prohibited this instance from being saved:</h2>

      <ul>
      <% @instance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :launch_time %><br>
    <%= f.datetime_select :launch_time %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instances/edit.html.erb
<h1>Editing Instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance %> |
<%= link_to 'Back', instances_path %>

app/views/instances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Instances</h1>

<table>
  <thead>
    <tr>
      <th>Ip address</th>
      <th>Image</th>
      <th>Launch time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instances.each do |instance| %>
      <tr>
        <td><%= instance.ip_address %></td>
        <td><%= instance.image %></td>
        <td><%= instance.launch_time %></td>
        <td><%= instance.status %></td>
        <td><%= link_to 'Show', instance %></td>
        <td><%= link_to 'Edit', edit_instance_path(instance) %></td>
        <td><%= link_to 'Destroy', instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instance', new_instance_path %>

app/views/instances/new.html.erb
<h1>New Instance</h1>

<%= render 'form' %>

<%= link_to 'Back', instances_path %>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip address:</strong>
  <%= @instance.ip_address %>
</p>

<p>
  <strong>Image:</strong>
  <%= @instance.image %>
</p>

<p>
  <strong>Launch time:</strong>
  <%= @instance.launch_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @instance.status %>
</p>

<%= link_to 'Edit', edit_instance_path(@instance) %> |
<%= link_to 'Back', instances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maas</title>
  
  <!--link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">

<%= yield %>

</div>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maas</title>
  <!--link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="http://jsontoyaml.com/js/json2yaml.js"></script>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">

<%= yield %>

</div>
<%= javascript_include_tag "application" , :media => "all"%>
</body>
</html>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :varable %><br>
    <%= f.text_field :varable %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>Varable</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.varable %></td>
        <td><%= property.value %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Varable:</strong>
  <%= @property.varable %>
</p>

<p>
  <strong>Value:</strong>
  <%= @property.value %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/session/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Please Sign In</h3>
      </div>
      <div class="panel-body">
<%= form_tag("/login", method:"post") do  %>
            <fieldset>
              <div class="form-group">
					Email<br />
                 <%= text_field_tag :email%>
              </div>

              <div class="form-group">
                Password<br />
                <%= password_field_tag :password%>
              </div>

              <div class="actions">
                <%= submit_tag "Log in", class: 'btn btn-default btn-success btn-block'%>
              </div>
        </fieldset>
<% end %>
        </div>
      </div>
    </div>
</div>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>